### ISSUE TITLE
Problem: Write Documentation for Ecko Plugins Stripe

### ISSUE THREAD

**Issue by Mansh05** [magicstone-dev/ecko-plugins#3]
Stripe Documentation oh now to configure and make use of it needs to be written properly. This should written only after #2.

**Comment by weex** [comment]
Maybe solved with https://github.com/magicstone-dev/ecko/wiki/Sponsors-Plugin-Setup

**Comment by Mansh05** [comment]
Working on few docs changes @weex, will create a pr on this. Actually stripe work independently than that of sponsor so we need to write a different setup documentation for it actually.
